/// Flutter icons Plus
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Plus
///      fonts:
///       - asset: fonts/Plus.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Plus {
  Plus._();

  static const _kFontFam = 'Plus';
  static const String? _kFontPkg = null;
  static const IconData user_md = IconData(0xf0f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_check_o = IconData(0xf274, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xebab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
