part of 'shared.dart';

final myTextTheme = TextTheme(
  headline1: GoogleFonts.poppins(fontSize: 82, fontWeight: FontWeight.w300, letterSpacing: -1.5),
  headline2: GoogleFonts.poppins(fontSize: 48, fontWeight: FontWeight.w400, letterSpacing: -0.5, color: Colors.black),
  headline3: GoogleFonts.poppins(fontSize: 41, fontWeight: FontWeight.w700, letterSpacing: 1.5, color: Colors.black),
  headline4: GoogleFonts.poppins(fontSize: 29, fontWeight: FontWeight.w700, letterSpacing: 0.25, color: Colors.black),
  headline5: GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w900, color: Colors.black),
  headline6: GoogleFonts.poppins(fontSize: 19, fontWeight: FontWeight.w700, letterSpacing: 0.15, color: Colors.black),
  subtitle1: GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w400, letterSpacing: 0.15),
  subtitle2: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w500, letterSpacing: 0.1),
  bodyText1: GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w400, color: Colors.black, letterSpacing: 0.5),
  bodyText2: GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.w400, color: Colors.grey, letterSpacing: 0.25),
  button: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w500, letterSpacing: 0.25, color: Color(0xFF98bd8f)),
  caption: GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w400, letterSpacing: 0.4),
  overline: GoogleFonts.poppins(fontSize: 9, fontWeight: FontWeight.w400, letterSpacing: 1.5),

  //                         color: Colors.black,
  // fontSize: 48,
  // fontWeight: FontWeight.w900,
  // letterSpacing: 1.5,
  // headline1: GoogleFonts.poppins(fontSize: 82, fontWeight: FontWeight.w300, letterSpacing: 1.5),
  // headline2: GoogleFonts.poppins(fontSize: 41, fontWeight: FontWeight.w700, letterSpacing: 1.5, color: Colors.black),
  // headline3: GoogleFonts.poppins(fontSize: 41, fontWeight: FontWeight.w400),
  // headline4: GoogleFonts.poppins(fontSize: 29, fontWeight: FontWeight.w400, letterSpacing: 0.25),
  // headline5: GoogleFonts.poppins(fontSize: 24, fontWeight: FontWeight.w900),
  // headline6: GoogleFonts.poppins(fontSize: 19, fontWeight: FontWeight.w700, letterSpacing: 0.15),
  // subtitle1: GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w400, letterSpacing: 0.15),
  // subtitle2: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w500, letterSpacing: 0.1),
  // bodyText1: GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w400, letterSpacing: 0.5),
  // bodyText2: GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.w400, letterSpacing: 0.25),
  // button: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w500, letterSpacing: 0.25, color: Color(0xFF49AFDB)),
  // caption: GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w400, letterSpacing: 0.4),
  // overline: GoogleFonts.poppins(fontSize: 9, fontWeight: FontWeight.w400, letterSpacing: 1.5),
);
